name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Migrate Biome schema
        run: pnpm biome migrate --write
      - name: Apply lint fixes
        run: pnpm lint:fix
      - name: Apply Knip fixes
        run: pnpm knip -- --fix
      - name: Run autofix.ci
        uses: autofix-ci/action@v1
        with:
          commit-message: "refactor: apply automatic fixes"
